# JBoss Enterprise Application Platform continuous delivery OpenShift container image

NOTE: Extends link:https://github.com/jboss-container-images/jboss-eap-7-image/tree/eap-cd[JBoss EAP CD container image]

## Importing Imagestreams and Templates

You should have the 'oc' tools available and be logged in to your OpenShift instance. For more details on how to do this, please consult the OpenShift documentation.
For example, for OpenShift Online, see: https://docs.openshift.com/online/cli_reference/get_started_cli.html
[source, bash]
----
for resource in eap-cd-image-stream.json \
  eap-cd-amq-persistent-s2i.json \
  eap-cd-amq-s2i.json \
  eap-cd-basic-s2i.json \
  eap-cd-https-s2i.json \
  eap-cd-sso-s2i.json \
  eap-cd-third-party-db-s2i.json \
  eap-cd-tx-recovery-s2i.json
do
  oc replace --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-eap-7-openshift-image/eap-cd/templates/${resource}
done
----

If you have administrative access to the general `openshift` namespace and want the image streams and templates to be accessible by all projects, add -n openshift to the oc replace line of the command. For example:

[source, bash]
----
oc replace -n openshift --force -f ...
----

See https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform_continuous_delivery/17/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/#import_imagestreams_templates for more details on importing templates.

#### Updating Existing Images
To update an to the most recent image:

[source, bash]
----
oc import-image eap-cd-openshift:17
----

Optionally include namespace to the import:
[source, bash]
----
oc -n myproject import-image eap-cd-openshift:17
----

#### Creating New Applications With Templates
Example:

[source, bash]
----
oc -n myproject new-app eap-cd-basic-s2i -p APPLICATION_NAME=eap-cd-basic-app
----

or, if a namespace was used with `-n` above:
[source, bash]
----
oc -n myproject new-app eap-cd-basic-s2i -p APPLICATION_NAME=eap-cd-basic-app -p IMAGE_STREAM_NAMESPACE=myproject
----

For more information on application creation and deployment see: https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform_continuous_delivery/17/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/#deploy_eap_s2i

## Creating Secrets

Some of the included templates require the creation of secrets.

Example:
[source, bash]
----
$ keytool -genkey -keyalg RSA -alias eapdemo-selfsigned -keystore keystore.jks -validity 360 -keysize 2048
$ oc secrets new eap7-app-secret keystore.jks
----

Example secrets may also be found here: https://github.com/jboss-openshift/application-templates/tree/master/secrets

[source, bash]
----
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/eap-app-secret.json
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/eap7-app-secret.json
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/sso-app-secret.json
----

Please refer to the EAP CD Documentation for additional details.

https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform_continuous_delivery/17/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/#prepare_for_deployment

## License

See link:LICENSE[LICENSE] file.

