# Red Hat JBoss Enterprise Application Platform 7.2 OpenShift container image

## Importing Imagestreams and Templates

You should have the 'oc' tools available and be logged in to your OpenShift instance. For more details on how to do this, please consult the OpenShift documentation.
For example, for OpenShift Online, see: https://docs.openshift.com/online/cli_reference/get_started_cli.html
[source, bash]
----
for resource in eap72-opendjk11-image-stream.json \
  eap72-openjdk11-amq-persistent-s2i.json \
  eap72-openjdk11-amq-s2i.json \
  eap72-openjdk11-basic-s2i.json \
  eap72-openjdk11-https-s2i.json \
  eap72-openjdk11-sso-s2i.json \
  eap72-openjdk11-third-party-db-s2i.json \
  eap72-openjdk11-tx-recovery-s2i.json
do
  oc replace --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-eap-7-openshift-image/eap72-openjdk11-ubi8/templates/${resource}
done
----

If you have administrative access to the general `openshift` namespace and want the image streams and templates to be accessible by all projects, add -n openshift to the oc replace line of the command. For example:

[source, bash]
----
oc replace -n openshift --force -f ...
----

See https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/red_hat_jboss_enterprise_application_platform_for_openshift/build_run_java_app_s2i#import_imagestreams_templates for more details on importing templates.

#### Updating Existing Images
To update an to the most recent image:

[source, bash]
----
oc import-image jboss-eap72-openjdk11-rhel8-openshift:1.1
----

Optionally include namespace to the import:
[source, bash]
----
oc -n myproject import-image jboss-eap72-openjdk11-rhel8-openshift:1.1
----

#### Creating New Applications With Templates
Example:

[source, bash]
----
oc -n myproject new-app eap72-openjdk11-basic-s2i -p APPLICATION_NAME=eap72-basic-app
----

or, if a namespace was used with `-n` above:
[source, bash]
----
oc -n myproject new-app eap72-openjdk11-basic-s2i -p APPLICATION_NAME=eap72-basic-app -p IMAGE_STREAM_NAMESPACE=myproject
----

For more information on application creation and deployment see: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/red_hat_jboss_enterprise_application_platform_for_openshift/build_run_java_app_s2i#deploy_eap_s2i

## Creating Secrets

Some of the included templates require the creation of secrets.

Example:
[source, bash]
----
$ keytool -genkey -keyalg RSA -alias eapdemo-selfsigned -keystore keystore.jks -validity 360 -keysize 2048
$ oc secrets new eap7-app-secret keystore.jks
----

Example secrets may also be found here: https://github.com/jboss-openshift/application-templates/tree/master/secrets

[source, bash]
----
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/eap-app-secret.json
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/eap7-app-secret.json
oc create -n myproject -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/secrets/sso-app-secret.json
----

Please refer to the Red Hat EAP on OpenShift Documentation for additional details.

https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/red_hat_jboss_enterprise_application_platform_for_openshift/build_run_java_app_s2i#prepare_for_deployment

## License

See link:LICENSE[LICENSE] file.

